#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SlidingMenuDemo.Resource", IsApplication=true)]

namespace SlidingMenuDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int list_padding = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int shadow_width = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int slidingmenu_offset = 2131034112;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int eagle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flamingo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int heron = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_github = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int indicator = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int new_indicator = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int octocat = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int octocat_scaled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ostrich = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int peacock = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int penguin = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Shadow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int shadowright = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int toucan = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int turkey = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int vulture = 2130837521;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int MyButton = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int fullscreen = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int left = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int margin = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int right = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int row_icon = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int row_title = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int selected_view = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int slidingmenumain = 2130968584;
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int num_cols = 2131099648;
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int slidingmenumain = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int Title = 2131165186;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
